# Generated by Django 5.2.12 on 2026-04-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='taille',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='tailles',
            field=models.CharField(blank=True, default='', help_text='ex: S,M,L,XL,XXL', max_length=200),
        ),
    ]
