# Generated by Django 5.2.12 on 2026-04-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_lignecommande_taille_produit_tailles'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.CharField(blank=True, choices=[('jebba_f', 'Jebba Femme'), ('dengri_f', 'Dengri Femme'), ('kachabiya_f', 'Kachabiya Femme'), ('cape', 'Cape'), ('kamis_f', 'Kamis Femme'), ('herga_h', 'Herga Homme'), ('dengri_h', 'Dengri Homme'), ('burnous', 'Burnous'), ('jebba_e', 'Jebba Enfant'), ('dengri_e', 'Dengri Enfant'), ('kachabiya_e', 'Kachabiya Enfant'), ('herga_e', 'Herga Enfant'), ('autre', 'Autre')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('femme', 'Femme'), ('homme', 'Homme'), ('enfants', 'Enfants')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='tailles',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
