# Generated by Django 5.2.12 on 2026-04-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_produit_sous_categorie_alter_produit_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='tailles',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='couleur',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='taille',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ProduitVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=100)),
                ('taille', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='boutique.produit')),
            ],
            options={
                'unique_together': {('produit', 'couleur', 'taille')},
            },
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.produitvariant'),
        ),
    ]
