# Generated by Django 5.2.12 on 2026-04-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_remove_produit_tailles_lignecommande_couleur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='couleur',
        ),
        migrations.AlterUniqueTogether(
            name='produitvariant',
            unique_together={('produit', 'taille')},
        ),
        migrations.RemoveField(
            model_name='produitvariant',
            name='couleur',
        ),
    ]
