# Generated by Django 5.2.12 on 2026-04-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_remove_lignecommande_couleur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='image',
            field=models.ImageField(default='', upload_to='produits/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutique.produit')),
            ],
        ),
    ]
