# Generated by Django 5.2.12 on 2026-04-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0006_lignecommande_image_produitimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lignecommande",
            name="image",
        ),
        migrations.AddField(
            model_name="produitimage",
            name="image",
            field=models.ImageField(default="", upload_to="produits/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("confirme", "Confirme"),
                    ("livre", "Livre"),
                    ("annule", "Annule"),
                ],
                default="nouveau",
                max_length=20,
            ),
        ),
    ]
