# Generated by Django 5.2.12 on 2026-04-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0007_remove_lignecommande_image_produitimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="couleur",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("confirme", "Confirmé"),
                    ("livre", "Livré"),
                    ("annule", "Annulé"),
                ],
                default="nouveau",
                max_length=20,
            ),
        ),
    ]
