# Generated by Django 6.0.4 on 2026-04-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0008_produit_couleur_alter_commande_statut"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="produitvariant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lignecommande",
            name="couleur",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="produitvariant",
            name="couleur",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="produitvariant",
            unique_together={("produit", "taille", "couleur")},
        ),
    ]
